---
driver:
  name: vagrant
  customize:
    memory: 256

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-7.8
  - name: centos-7.0

suites:
- name: package
  run_list:
    - recipe[mono4]
  attributes:
    mono4:
      install_method: package
- name: source
  run_list:
    - recipe[mono4]
  attributes:
    mono4:
      install_method: source
